### ISSUE TITLE
SSG vs. SSR

### ISSUE THREAD

**Issue by mitchierichie** [shshaw/next-apollo-ssr#2]
Would this approach work for SSG, or only SSR? I don't like the duplicated code and duplicated queries that comes with using getStaticProps, but am struggling to find a simpler approach whereby I can cache my query results server-side.

**Comment by jayy-lmao** [comment]
It will work for SSR. It can work for SSG so long as your Query/Mutation doesn't rely on any `variables` passed down from `ctx.req, ctx.query, ctx.res`. Looks to me like `_document` gets run before any of the `getServerSideProps` do. And I just gave it a test then 🤷 

[Update: New update: interestingly if you use `useRouter` it's fine! Crazy :o 
So SSR is okay, so long as you get your variables through useRouter]

**Comment by jayy-lmao** [comment]
New update: interestingly if you use `useRouter` it's fine! Crazy :o

**Comment by medv** [comment]
Works well for SSR so far. Using the project as is caused a hard location change to the desired route (using Link or otherwise), but adding even a blank `getServerSideProps() { return { props: {} } }` to each page solved this. `useRouter()` works as well. Hopefully this holds up, about to dig up a lot of trenches to solve this whole problem on a project :)
